# Use the official RabbitMQ image (with management plugin)
FROM rabbitmq:3-management

# Set environment variables (optional)
ENV RABBITMQ_DEFAULT_USER=myuser
ENV RABBITMQ_DEFAULT_PASS=mypassword

# Expose RabbitMQ management UI port and default port
EXPOSE 15672 5672