apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-clipsify-net
  namespace: default
spec:
  secretName: www-clipsify-net-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - www.clipsify.net
