apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: clipify.azurecr.io/gateway
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: MONGO-CONNECTION-STRING
                  key: MONGO-CONNECTION-STRING
            - name: APP_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: APP-SECRET-KEY
                  key: APP-SECRET-KEY
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: AUTH0-DOMAIN
                  key: AUTH0-DOMAIN
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: AUTH0-CLIENT-SECRET
                  key: AUTH0-CLIENT-SECRET
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: AUTH0-CLIENT-ID
                  key: AUTH0-CLIENT-ID
          envFrom:
            - configMapRef:
                name: gateway-configmap
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"
