apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: clipify.azurecr.io/gateway
          env:
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: kv-secrets
                  key: mongo-connection-string
            - name: APP_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: kv-secrets
                  key: app-secret-key
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: kv-secrets
                  key: auth0-domain
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kv-secrets
                  key: auth0-client-secret
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: kv-secrets
                  key: auth0-client-id
          envFrom:
            - configMapRef:
                name: gateway-configmap