# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"                                  # Set to true for using managed identity
    userAssignedIdentityID: 6dcab3b4-ef89-4820-80bb-3c73007570e3  # Set the clientID of the user-assigned managed identity to use
    keyvaultName: kv-clipify              # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: MONGO-CONNECTION-STRING
          objectType: secret              
          objectVersion: ""               
        - |
          objectName: APP-SECRET-KEY
          objectType: secret
          objectVersion: ""
        - |
          objectName: AUTH0-DOMAIN
          objectType: secret              
          objectVersion: ""               
        - |
          objectName: AUTH0-CLIENT-SECRET
          objectType: secret
          objectVersion: ""
        - |
          objectName: AUTH0-CLIENT-ID
          objectType: secret
          objectVersion: ""
    tenantId: b7d7e9a7-eb2c-4de0-a460-f7cf1d5c2b12