apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
spec:
  replicas: 2  # Increased for production
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth
        image: tim5672s/clipsify-auth:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: PORT
        - name: AUTH0_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: AUTH0_DOMAIN
        - name: APP_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: APP_SECRET_KEY
        - name: AUTH0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: AUTH0_CLIENT_ID
        - name: AUTH0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: AUTH0_CLIENT_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5




