name: Docker Auth-Services Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: 
        cd app/auth &&
        docker build . --file Dockerfile --tag auth:latest

    - name: Publish to Docker Hub
      uses: docker/build-push-action@v1     
      with:       
       username: ${{ secrets.DOCKER_HUB_USERNAME }} 
       password:  ${{ secrets.DOCKER_HUB_PASSWORD }}
       repository: tim5672s/auth       
       tags: ${{github.run_number}}
